spring:
  application:
    name: ddns
  native:
    mode: build

config:
  # accessKeyId 和 accessKeySecret 是否加密
  encryption: true
  # 指定网卡的mac地址，用于复杂网络环境下，程序可能获取不到正确的网卡，因此可以手动指定,非必填。
  fixedNetworkCardMacAddress: 00-00-00-00-00-0
  DomainNameServiceConfig:
    # 支持多账号，并且一组密钥对可以管理多个域名
    - accessKeyId: OzQ8QAmfV1Vx0VLRfqx+tIWo+jb
      accessKeySecret: /XROc3a3Ffesp0O05iFVnvfYOcZiM
      # 域名解析服务提供商类型
      domainNameServiceProviderType: aliyun
      # 多个域名配置
      domains:
        - domain: example1.com
          subDomain: dev
          # 域名解析的更新间隔时间，单位：分,非必填，默认为10分钟
          interval: 120